
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=[],ca="./this.program",k=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,r="",fa,u,v,fs,w,ha;
if(ea)r=l?require("path").dirname(r)+"/":__dirname+"/",ha=()=>{w||(fs=require("fs"),w=require("path"))},fa=function(a,b){ha();a=w.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")},v=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a},u=(a,b,c)=>{ha();a=w.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),ba=process.argv.slice(2),"undefined"!=typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof
x))throw a;}),process.on("unhandledRejection",function(a){throw a;}),k=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;b instanceof x||y("exiting due to exception: "+b);process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(da||l)l?r=self.location.href:"undefined"!=typeof document&&document.currentScript&&(r=document.currentScript.src),r=0!==r.indexOf("blob:")?r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);
b.send(null);return b.responseText},l&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),u=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};f.print||console.log.bind(console);var y=f.printErr||console.warn.bind(console);Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);
f.thisProgram&&(ca=f.thisProgram);f.quit&&(k=f.quit);var z;f.wasmBinary&&(z=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&A("no native wasm support detected");var ia,ja=!1;
function ka(a,b,c){var d={string:function(n){var p=0;if(null!==n&&void 0!==n&&0!==n){var t=(n.length<<2)+1;p=B(t);C(n,D,p,t)}return p},array:function(n){var p=B(n.length);la.set(n,p);return p}};a=f["_"+a];var e=[],h=0;if(c)for(var g=0;g<c.length;g++){var m=d[b[g]];m?(0===h&&(h=ma()),e[g]=m(c[g])):e[g]=c[g]}b=a.apply(null,e);b=function(n){0!==h&&na(h);return n}(b)}var oa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function E(a,b){if(a){var c=D,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&oa)a=oa.decode(c.subarray(a,b));else{for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}a=d}}else a="";return a}
function C(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function pa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var la,D,qa,ra,F,sa,G,H,I,ta=[],ua=[],va=[],wa=[],xa=[];function ya(){var a=f.preRun.shift();ta.unshift(a)}var J=0,za=null,K=null;function A(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";y(a);ja=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}
function Aa(){return L.startsWith("data:application/octet-stream;base64,")}var L;L="qoiview.wasm";if(!Aa()){var Ba=L;L=f.locateFile?f.locateFile(Ba,r):r+Ba}function Ca(){var a=L;try{if(a==L&&z)return new Uint8Array(z);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function Da(){if(!z&&(da||l)){if("function"==typeof fetch&&!L.startsWith("file://"))return fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Ca()});if(u)return new Promise(function(a,b){u(L,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ca()})}function Ea(a){for(;0<a.length;)a.shift()(f)}var Fa=0;
function Ga(){for(var a=N.length-1;0<=a;--a)Ha(a);N=[];Ia=[]}var Ia=[];function Ja(){if(Fa&&Ka.Qb)for(var a=0;a<Ia.length;++a){var b=Ia[a];Ia.splice(a,1);--a;b.zc.apply(null,b.qc)}}var N=[];function Ha(a){var b=N[a];b.target.removeEventListener(b.Jb,b.lc,b.Kb);N.splice(a,1)}
function O(a){function b(d){++Fa;Ka=a;Ja();a.Mb(d);Ja();--Fa}if(a.Lb)a.lc=b,a.target.addEventListener(a.Jb,b,a.Kb),N.push(a),La||(wa.push(Ga),La=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].Jb==a.Jb&&Ha(c--)}function Ma(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var La,Ka,Na,Oa,Pa,Qa,Ra,Sa,Ta,Ua=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];
function P(a){a=2<a?E(a):a;return Ua[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function Va(a){return 0>Ua.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function Wa(a,b,c,d,e,h){Na||(Na=Q(256));a={target:P(a),Jb:h,Lb:d,Mb:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=Na;C(Ma(g.target),D,n+0,128);C(m,D,n+128,128);I.get(d)(e,n,b)&&g.preventDefault()},Kb:c};O(a)}
function Xa(a,b,c,d,e,h){Oa||(Oa=Q(176));a={target:P(a),Qb:!0,Jb:h,Lb:d,Mb:function(g){var m=Oa;H[m>>3]=g.timeStamp;var n=m>>2;F[n+2]=g.location;F[n+3]=g.ctrlKey;F[n+4]=g.shiftKey;F[n+5]=g.altKey;F[n+6]=g.metaKey;F[n+7]=g.repeat;F[n+8]=g.charCode;F[n+9]=g.keyCode;F[n+10]=g.which;C(g.key||"",D,m+44,32);C(g.code||"",D,m+76,32);C(g.char||"",D,m+108,32);C(g.locale||"",D,m+140,32);I.get(d)(e,m,b)&&g.preventDefault()},Kb:c};O(a)}
function Ya(a,b,c){H[a>>3]=b.timeStamp;a>>=2;F[a+2]=b.screenX;F[a+3]=b.screenY;F[a+4]=b.clientX;F[a+5]=b.clientY;F[a+6]=b.ctrlKey;F[a+7]=b.shiftKey;F[a+8]=b.altKey;F[a+9]=b.metaKey;qa[2*a+20]=b.button;qa[2*a+21]=b.buttons;F[a+11]=b.movementX;F[a+12]=b.movementY;c=Va(c);F[a+13]=b.clientX-c.left;F[a+14]=b.clientY-c.top}
function R(a,b,c,d,e,h){Pa||(Pa=Q(72));a=P(a);O({target:a,Qb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Jb:h,Lb:d,Mb:function(g){g=g||event;Ya(Pa,g,a);I.get(d)(e,Pa,b)&&g.preventDefault()},Kb:c})}function Za(a,b,c,d,e){Qa||(Qa=Q(260));O({target:a,Jb:e,Lb:d,Mb:function(h){h=h||event;var g=Qa,m=document.pointerLockElement||document.Nb||document.Yb||document.Xb;F[g>>2]=!!m;var n=m&&m.id?m.id:"";C(Ma(m),D,g+4,128);C(n,D,g+132,128);I.get(d)(20,g,b)&&h.preventDefault()},Kb:c})}
function $a(a,b,c,d,e){O({target:a,Jb:e,Lb:d,Mb:function(h){h=h||event;I.get(d)(38,0,b)&&h.preventDefault()},Kb:c})}
function ab(a,b,c,d){Ra||(Ra=Q(36));a=P(a);O({target:a,Jb:"resize",Lb:d,Mb:function(e){e=e||event;if(e.target==a){var h=document.body;if(h){var g=Ra;F[g>>2]=e.detail;F[g+4>>2]=h.clientWidth;F[g+8>>2]=h.clientHeight;F[g+12>>2]=innerWidth;F[g+16>>2]=innerHeight;F[g+20>>2]=outerWidth;F[g+24>>2]=outerHeight;F[g+28>>2]=pageXOffset;F[g+32>>2]=pageYOffset;I.get(d)(10,g,b)&&e.preventDefault()}}},Kb:c})}
function bb(a,b,c,d,e,h){Sa||(Sa=Q(1696));a=P(a);O({target:a,Qb:"touchstart"==h||"touchend"==h,Jb:h,Lb:d,Mb:function(g){for(var m,n={},p=g.touches,t=0;t<p.length;++t)m=p[t],m.$b=m.ac=0,n[m.identifier]=m;for(t=0;t<g.changedTouches.length;++t)m=g.changedTouches[t],m.$b=1,n[m.identifier]=m;for(t=0;t<g.targetTouches.length;++t)n[g.targetTouches[t].identifier].ac=1;p=Sa;H[p>>3]=g.timeStamp;var q=p>>2;F[q+3]=g.ctrlKey;F[q+4]=g.shiftKey;F[q+5]=g.altKey;F[q+6]=g.metaKey;q+=7;var M=Va(a),jb=0;for(t in n)if(m=
n[t],F[q]=m.identifier,F[q+1]=m.screenX,F[q+2]=m.screenY,F[q+3]=m.clientX,F[q+4]=m.clientY,F[q+5]=m.pageX,F[q+6]=m.pageY,F[q+7]=m.$b,F[q+8]=m.ac,F[q+9]=m.clientX-M.left,F[q+10]=m.clientY-M.top,q+=13,31<++jb)break;F[p+8>>2]=jb;I.get(d)(e,p,b)&&g.preventDefault()},Kb:c})}function cb(a,b,c,d,e,h){a={target:P(a),Jb:h,Lb:d,Mb:function(g){g=g||event;I.get(d)(e,0,b)&&g.preventDefault()},Kb:c};O(a)}
function db(a,b,c,d){Ta||(Ta=Q(104));O({target:a,Qb:!0,Jb:"wheel",Lb:d,Mb:function(e){e=e||event;var h=Ta;Ya(h,e,a);H[h+72>>3]=e.deltaX;H[h+80>>3]=e.deltaY;H[h+88>>3]=e.deltaZ;F[h+96>>2]=e.deltaMode;I.get(d)(9,h,b)&&e.preventDefault()},Kb:c})}
function eb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,g){b.drawElementsInstancedANGLE(c,d,e,h,g)})}
function fb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function gb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function hb(a){a.vc=a.getExtension("WEBGL_multi_draw")}
var ib=1,kb=[],S=[],lb=[],mb=[],nb=[],T=[],ob=[],pb={};function U(a){qb||(qb=a)}function rb(a){for(var b=ib++,c=a.length;c<b;c++)a[c]=null;return b}function sb(a,b){a.Nb||(a.Nb=a.getContext,a.getContext=function(d,e){e=a.Nb(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?tb(c,b):0}function tb(a,b){var c=rb(ob),d={tc:c,attributes:b,version:b.oc,Ub:a};a.canvas&&(a.canvas.pc=d);ob[c]=d;("undefined"==typeof b.Zb||b.Zb)&&ub(d);return c}
function ub(a){a||(a=vb);if(!a.nc){a.nc=!0;var b=a.Ub;eb(b);fb(b);gb(b);b.sc=b.getExtension("EXT_disjoint_timer_query");hb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var qb,vb,wb=["default","low-power","high-performance"];function xb(a,b,c,d){for(var e=0;e<a;e++){var h=V[c](),g=h&&rb(d);h?(h.name=g,d[g]=h):U(1282);F[b+4*e>>2]=g}}
function yb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=V.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=V.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:U(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)F[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U(1280);y("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:U(1280);y("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}F[b>>2]=c}else U(1281)}function zb(a){var b=pa(a)+1,c=Q(b);C(a,D,c,b);return c}
function Ab(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function W(a){var b=V.kc;if(b){var c=b.Pb[a];"number"==typeof c&&(b.Pb[a]=c=V.getUniformLocation(b,b.ic[a]+(0<c?"["+c+"]":"")));return c}U(1282)}for(var X=[],Y=[],V,Bb=new Float32Array(288),Z=0;288>Z;++Z)X[Z]=Bb.subarray(0,Z+1);var Cb=new Int32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Cb.subarray(0,Z+1);
var Mb={M:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},$:function(a,b,c){a=P(a);if(!a)return-4;a=Va(a);H[b>>3]=a.width;H[c>>3]=a.height;return 0},Ra:function(a,b,c){D.copyWithin(a,b,b+c)},za:function(a,b){function c(d){I.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Qa:function(){A("OOM")},I:function(a,b,c,d){Wa(a,b,c,d,12,"blur");return 0},F:function(a,b,c){a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},J:function(a,b,c,d){Wa(a,b,c,d,13,
"focus");return 0},T:function(a,b,c,d){Xa(a,b,c,d,2,"keydown");return 0},R:function(a,b,c,d){Xa(a,b,c,d,1,"keypress");return 0},S:function(a,b,c,d){Xa(a,b,c,d,3,"keyup");return 0},Z:function(a,b,c,d){R(a,b,c,d,5,"mousedown");return 0},W:function(a,b,c,d){R(a,b,c,d,33,"mouseenter");return 0},V:function(a,b,c,d){R(a,b,c,d,34,"mouseleave");return 0},X:function(a,b,c,d){R(a,b,c,d,8,"mousemove");return 0},Y:function(a,b,c,d){R(a,b,c,d,6,"mouseup");return 0},L:function(a,b,c,d){if(!document||!document.body||
!(document.body.requestPointerLock||document.body.Nb||document.body.Yb||document.body.Xb))return-1;a=P(a);if(!a)return-4;Za(a,b,c,d,"pointerlockchange");Za(a,b,c,d,"mozpointerlockchange");Za(a,b,c,d,"webkitpointerlockchange");Za(a,b,c,d,"mspointerlockchange");return 0},K:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Nb||document.body.Yb||document.body.Xb))return-1;a=P(a);if(!a)return-4;$a(a,b,c,d,"pointerlockerror");$a(a,b,c,d,"mozpointerlockerror");$a(a,b,c,d,
"webkitpointerlockerror");$a(a,b,c,d,"mspointerlockerror");return 0},Ma:function(a,b,c,d){ab(a,b,c,d);return 0},N:function(a,b,c,d){bb(a,b,c,d,25,"touchcancel");return 0},O:function(a,b,c,d){bb(a,b,c,d,23,"touchend");return 0},P:function(a,b,c,d){bb(a,b,c,d,24,"touchmove");return 0},Q:function(a,b,c,d){bb(a,b,c,d,22,"touchstart");return 0},H:function(a,b,c,d){cb(a,b,c,d,31,"webglcontextlost");return 0},G:function(a,b,c,d){cb(a,b,c,d,32,"webglcontextrestored");return 0},U:function(a,b,c,d){a=P(a);
return"undefined"!=typeof a.onwheel?(db(a,b,c,d),0):-1},_:function(a,b){b>>=2;b={alpha:!!F[b],depth:!!F[b+1],stencil:!!F[b+2],antialias:!!F[b+3],premultipliedAlpha:!!F[b+4],preserveDrawingBuffer:!!F[b+5],powerPreference:wb[F[b+6]],failIfMajorPerformanceCaveat:!!F[b+7],oc:F[b+8],uc:F[b+9],Zb:F[b+10],mc:F[b+11],wc:F[b+12],xc:F[b+13]};a=P(a);return!a||b.mc?0:sb(a,b)},Na:function(a,b){a=ob[a];b=E(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&eb(V);"OES_vertex_array_object"==b&&
fb(V);"WEBGL_draw_buffers"==b&&gb(V);"WEBGL_multi_draw"==b&&hb(V);return!!a.Ub.getExtension(b)},Pa:function(a){a>>=2;for(var b=0;14>b;++b)F[a+b]=0;F[a]=F[a+1]=F[a+3]=F[a+4]=F[a+8]=F[a+10]=1},Oa:function(a){vb=ob[a];f.rc=V=vb&&vb.Ub;return!a||V?0:-5},D:function(a){V.activeTexture(a)},u:function(a,b){V.attachShader(S[a],T[b])},f:function(a,b){V.bindBuffer(a,kb[b])},q:function(a,b){V.bindFramebuffer(a,lb[b])},qa:function(a,b){V.bindRenderbuffer(a,mb[b])},e:function(a,b){V.bindTexture(a,nb[b])},y:function(a,
b,c,d){V.blendColor(a,b,c,d)},z:function(a,b){V.blendEquationSeparate(a,b)},A:function(a,b,c,d){V.blendFuncSeparate(a,b,c,d)},sa:function(a,b,c,d){V.bufferData(a,c?D.subarray(c,c+b):b,d)},j:function(a,b,c,d){V.bufferSubData(a,b,D.subarray(d,d+c))},kb:function(a){V.clear(a)},aa:function(a,b,c,d){V.clearColor(a,b,c,d)},mb:function(a){V.clearDepth(a)},lb:function(a){V.clearStencil(a)},g:function(a,b,c,d){V.colorMask(!!a,!!b,!!c,!!d)},da:function(a){V.compileShader(T[a])},ma:function(a,b,c,d,e,h,g,m){V.compressedTexImage2D(a,
b,c,d,e,h,m?D.subarray(m,m+g):null)},ka:function(){var a=rb(S),b=V.createProgram();b.name=a;b.Tb=b.Rb=b.Sb=0;b.Wb=1;S[a]=b;return a},fa:function(a){var b=rb(T);T[b]=V.createShader(a);return b},v:function(a){V.cullFace(a)},Aa:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],e=kb[d];e&&(V.deleteBuffer(e),e.name=0,kb[d]=null)}},n:function(a,b){for(var c=0;c<a;++c){var d=F[b+4*c>>2],e=lb[d];e&&(V.deleteFramebuffer(e),e.name=0,lb[d]=null)}},C:function(a){if(a){var b=S[a];b?(V.deleteProgram(b),b.name=
0,S[a]=null):U(1281)}},E:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],e=mb[d];e&&(V.deleteRenderbuffer(e),e.name=0,mb[d]=null)}},i:function(a){if(a){var b=T[a];b?(V.deleteShader(b),T[a]=null):U(1281)}},ya:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],e=nb[d];e&&(V.deleteTexture(e),e.name=0,nb[d]=null)}},m:function(a){V.depthFunc(a)},l:function(a){V.depthMask(!!a)},a:function(a){V.disable(a)},B:function(a){V.disableVertexAttribArray(a)},Sa:function(a,b,c){V.drawArrays(a,b,c)},Ua:function(a,
b,c,d){V.drawArraysInstanced(a,b,c,d)},Va:function(a,b,c,d){V.drawElements(a,b,c,d)},Wa:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},c:function(a){V.enable(a)},fb:function(a){V.enableVertexAttribArray(a)},w:function(a){V.frontFace(a)},ta:function(a,b){xb(a,b,"createBuffer",kb)},ra:function(a,b){xb(a,b,"createRenderbuffer",mb)},oa:function(a,b){xb(a,b,"createTexture",nb)},ba:function(a,b){return V.getAttribLocation(S[a],E(b))},b:function(a,b){yb(a,b)},ia:function(a,b,c,d){a=V.getProgramInfoLog(S[a]);
null===a&&(a="(unknown error)");b=0<b&&d?C(a,D,d,b):0;c&&(F[c>>2]=b)},t:function(a,b,c){if(c)if(a>=ib)U(1281);else if(a=S[a],35716==b)a=V.getProgramInfoLog(a),null===a&&(a="(unknown error)"),F[c>>2]=a.length+1;else if(35719==b){if(!a.Tb)for(b=0;b<V.getProgramParameter(a,35718);++b)a.Tb=Math.max(a.Tb,V.getActiveUniform(a,b).name.length+1);F[c>>2]=a.Tb}else if(35722==b){if(!a.Rb)for(b=0;b<V.getProgramParameter(a,35721);++b)a.Rb=Math.max(a.Rb,V.getActiveAttrib(a,b).name.length+1);F[c>>2]=a.Rb}else if(35381==
b){if(!a.Sb)for(b=0;b<V.getProgramParameter(a,35382);++b)a.Sb=Math.max(a.Sb,V.getActiveUniformBlockName(a,b).length+1);F[c>>2]=a.Sb}else F[c>>2]=V.getProgramParameter(a,b);else U(1281)},ca:function(a,b,c,d){a=V.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,D,d,b):0;c&&(F[c>>2]=b)},r:function(a,b,c){c?35716==b?(a=V.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),F[c>>2]=a?a.length+1:0):35720==b?(a=V.getShaderSource(T[a]),F[c>>2]=a?a.length+1:0):F[c>>2]=V.getShaderParameter(T[a],
b):U(1281)},Ba:function(a){var b=pb[a];if(!b){switch(a){case 7939:b=V.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=zb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=V.getParameter(a))||U(1280);b=b&&zb(b);break;case 7938:b=zb("OpenGL ES 2.0 ("+V.getParameter(7938)+")");break;case 35724:b=V.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=
zb(b);break;default:U(1280)}pb[a]=b}return b},s:function(a,b){b=E(b);if(a=S[a]){var c=a,d=c.Pb,e=c.jc,h;if(!d)for(c.Pb=d={},c.ic={},h=0;h<V.getProgramParameter(c,35718);++h){var g=V.getActiveUniform(c,h);var m=g.name;g=g.size;var n=Ab(m);n=0<n?m.slice(0,n):m;var p=c.Wb;c.Wb+=g;e[n]=[g,p];for(m=0;m<g;++m)d[p]=m,c.ic[p++]=n}c=a.Pb;d=0;e=b;h=Ab(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.jc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||V.getUniformLocation(a,b)))return d}else U(1281);return-1},
ja:function(a){a=S[a];V.linkProgram(a);a.Pb=0;a.jc={}},x:function(a,b){V.polygonOffset(a,b)},pa:function(a,b,c,d){V.renderbufferStorage(a,b,c,d)},o:function(a,b,c,d){V.scissor(a,b,c,d)},ea:function(a,b,c,d){for(var e="",h=0;h<b;++h){var g=d?F[d+4*h>>2]:-1;e+=E(F[c+4*h>>2],0>g?void 0:g)}V.shaderSource(T[a],e)},wa:function(a,b,c){V.stencilFunc(a,b,c)},jb:function(a,b,c,d){V.stencilFuncSeparate(a,b,c,d)},k:function(a){V.stencilMask(a)},va:function(a,b,c){V.stencilOp(a,b,c)},ib:function(a,b,c,d){V.stencilOpSeparate(a,
b,c,d)},la:function(a,b,c,d,e,h,g,m,n){var p=V,t=p.texImage2D;if(n){var q=m-5120;q=1==q?D:4==q?F:6==q?G:5==q||28922==q?sa:ra;var M=31-Math.clz32(q.BYTES_PER_ELEMENT);n=q.subarray(n>>M,n+e*(d*({5:3,6:4,8:2,29502:3,29504:4}[g-6402]||1)*(1<<M)+4-1&-4)>>M)}else n=null;t.call(p,a,b,c,d,e,h,g,m,n)},d:function(a,b,c){V.texParameteri(a,b,c)},eb:function(a,b,c){if(288>=b)for(var d=X[b-1],e=0;e<b;++e)d[e]=G[c+4*e>>2];else d=G.subarray(c>>2,c+4*b>>2);V.uniform1fv(W(a),d)},ha:function(a,b){V.uniform1i(W(a),b)},
$a:function(a,b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=F[c+4*e>>2];else d=F.subarray(c>>2,c+4*b>>2);V.uniform1iv(W(a),d)},db:function(a,b,c){if(144>=b)for(var d=X[2*b-1],e=0;e<2*b;e+=2)d[e]=G[c+4*e>>2],d[e+1]=G[c+(4*e+4)>>2];else d=G.subarray(c>>2,c+8*b>>2);V.uniform2fv(W(a),d)},_a:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2];else d=F.subarray(c>>2,c+8*b>>2);V.uniform2iv(W(a),d)},bb:function(a,b,c){if(96>=b)for(var d=X[3*b-1],e=0;e<3*
b;e+=3)d[e]=G[c+4*e>>2],d[e+1]=G[c+(4*e+4)>>2],d[e+2]=G[c+(4*e+8)>>2];else d=G.subarray(c>>2,c+12*b>>2);V.uniform3fv(W(a),d)},Za:function(a,b,c){if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2];else d=F.subarray(c>>2,c+12*b>>2);V.uniform3iv(W(a),d)},ab:function(a,b,c){if(72>=b){var d=X[4*b-1],e=G;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=G.subarray(c>>2,c+16*b>>2);V.uniform4fv(W(a),d)},
Ya:function(a,b,c){if(72>=b)for(var d=Y[4*b-1],e=0;e<4*b;e+=4)d[e]=F[c+4*e>>2],d[e+1]=F[c+(4*e+4)>>2],d[e+2]=F[c+(4*e+8)>>2],d[e+3]=F[c+(4*e+12)>>2];else d=F.subarray(c>>2,c+16*b>>2);V.uniform4iv(W(a),d)},Xa:function(a,b,c,d){if(18>=b){var e=X[16*b-1],h=G;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=h[m];e[g+1]=h[m+1];e[g+2]=h[m+2];e[g+3]=h[m+3];e[g+4]=h[m+4];e[g+5]=h[m+5];e[g+6]=h[m+6];e[g+7]=h[m+7];e[g+8]=h[m+8];e[g+9]=h[m+9];e[g+10]=h[m+10];e[g+11]=h[m+11];e[g+12]=h[m+12];e[g+13]=h[m+13];e[g+
14]=h[m+14];e[g+15]=h[m+15]}}else e=G.subarray(d>>2,d+64*b>>2);V.uniformMatrix4fv(W(a),!!c,e)},h:function(a){a=S[a];V.useProgram(a);V.kc=a},gb:function(a,b){V.vertexAttribDivisor(a,b)},hb:function(a,b,c,d,e,h){V.vertexAttribPointer(a,b,c,!!d,e,h)},p:function(a,b,c,d){V.viewport(a,b,c,d)},La:function(){f.bc=function(a){0!=Db()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.bc)},Ka:function(){f.hc=function(a){a=a.clipboardData.getData("text");ka("_sapp_emsc_onpaste",
["string"],[a])};window.addEventListener("paste",f.hc)},Ja:function(a){f.yc=[];a=E(a);a=document.getElementById(a);f.cc=function(b){b.stopPropagation();b.preventDefault()};f.dc=function(b){b.stopPropagation();b.preventDefault()};f.ec=function(b){b.stopPropagation();b.preventDefault()};f.fc=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;f.Vb=c;Eb(c.length);var d;for(d=0;d<c.length;d++)ka("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Fb(b.clientX,b.clientY)};a.addEventListener("dragenter",
f.cc,!1);a.addEventListener("dragleave",f.dc,!1);a.addEventListener("dragover",f.ec,!1);a.addEventListener("drop",f.fc,!1)},xa:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ha:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Gb()});document.body.append(a)},na:function(a){return 0>a||a>=f.Vb.length?0:f.Vb[a].size},ga:function(a,b,c,d,e){var h=
new FileReader;h.onload=function(g){g=g.target.result;g.byteLength>d?Hb(a,0,1,b,0,c,d,e):(D.set(new Uint8Array(g),c),Hb(a,1,0,b,g.byteLength,c,d,e))};h.onerror=function(){Hb(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(f.Vb[a])},Ga:function(){document.getElementById("_sokol_app_input_element").focus()},ob:function(a){a=E(a);f.Ob=document.getElementById(a);f.Ob||console.log("sokol_app.h: invalid target:"+a);f.Ob.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},
Ea:function(){window.removeEventListener("beforeunload",f.bc)},Da:function(){window.removeEventListener("paste",f.hc)},Ca:function(a){a=E(a);a=document.getElementById(a);a.removeEventListener("dragenter",f.cc);a.removeEventListener("dragleave",f.dc);a.removeEventListener("dragover",f.ec);a.removeEventListener("drop",f.fc)},Ia:function(){f.Ob&&f.Ob.requestPointerLock&&f.Ob.requestPointerLock()},ua:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var e=d.getContext("2d"),
h=e.createImageData(a,b);h.data.set(D.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Fa:function(){document.getElementById("_sokol_app_input_element").blur()},nb:function(){for(var a=(new URLSearchParams(window.location.search)).entries(),b=a.next();!b.done;b=a.next())ka("_sargs_add_kvp",["string","string"],[b.value[0],b.value[1]])},cb:function(a,b,c,d,e,h){b=E(b);var g=new XMLHttpRequest;
g.open("GET",b);g.responseType="arraybuffer";var m=0<d;m&&g.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));g.onreadystatechange=function(){if(this.readyState==this.DONE)if(206==this.status||200==this.status&&!m){var n=new Uint8Array(g.response),p=n.length;p<=h?(D.set(n,e),Ib(a,d,p)):Jb(a)}else Kb(a,this.status)};g.send()},Ta:function(a,b){b=E(b);var c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(this.readyState==this.DONE)if(200==this.status){var d=this.getResponseHeader("Content-Length");
Lb(a,d)}else Kb(a,this.status)};c.send()}};
(function(){function a(e){f.asm=e.exports;ia=f.asm.pb;e=ia.buffer;f.HEAP8=la=new Int8Array(e);f.HEAP16=qa=new Int16Array(e);f.HEAP32=F=new Int32Array(e);f.HEAPU8=D=new Uint8Array(e);f.HEAPU16=ra=new Uint16Array(e);f.HEAPU32=sa=new Uint32Array(e);f.HEAPF32=G=new Float32Array(e);f.HEAPF64=H=new Float64Array(e);I=f.asm.Fb;ua.unshift(f.asm.qb);J--;f.monitorRunDependencies&&f.monitorRunDependencies(J);0==J&&(null!==za&&(clearInterval(za),za=null),K&&(e=K,K=null,e()))}function b(e){a(e.instance)}function c(e){return Da().then(function(h){return WebAssembly.instantiate(h,
d)}).then(function(h){return h}).then(e,function(h){y("failed to asynchronously prepare wasm: "+h);A(h)})}var d={a:Mb};J++;f.monitorRunDependencies&&f.monitorRunDependencies(J);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return y("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return z||"function"!=typeof WebAssembly.instantiateStreaming||Aa()||L.startsWith("file://")||ea||"function"!=typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(h){y("wasm streaming compile failed: "+h);y("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.qb).apply(null,arguments)};var Q=f._malloc=function(){return(Q=f._malloc=f.asm.rb).apply(null,arguments)},Gb=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Gb=f.__sapp_emsc_notify_keyboard_hidden=f.asm.sb).apply(null,arguments)};
f.__sapp_emsc_onpaste=function(){return(f.__sapp_emsc_onpaste=f.asm.tb).apply(null,arguments)};var Db=f.__sapp_html5_get_ask_leave_site=function(){return(Db=f.__sapp_html5_get_ask_leave_site=f.asm.ub).apply(null,arguments)},Eb=f.__sapp_emsc_begin_drop=function(){return(Eb=f.__sapp_emsc_begin_drop=f.asm.vb).apply(null,arguments)};f.__sapp_emsc_drop=function(){return(f.__sapp_emsc_drop=f.asm.wb).apply(null,arguments)};
var Fb=f.__sapp_emsc_end_drop=function(){return(Fb=f.__sapp_emsc_end_drop=f.asm.xb).apply(null,arguments)},Hb=f.__sapp_emsc_invoke_fetch_cb=function(){return(Hb=f.__sapp_emsc_invoke_fetch_cb=f.asm.yb).apply(null,arguments)};f._main=function(){return(f._main=f.asm.zb).apply(null,arguments)};f.__sargs_add_kvp=function(){return(f.__sargs_add_kvp=f.asm.Ab).apply(null,arguments)};
var Lb=f.__sfetch_emsc_head_response=function(){return(Lb=f.__sfetch_emsc_head_response=f.asm.Bb).apply(null,arguments)},Ib=f.__sfetch_emsc_get_response=function(){return(Ib=f.__sfetch_emsc_get_response=f.asm.Cb).apply(null,arguments)},Kb=f.__sfetch_emsc_failed_http_status=function(){return(Kb=f.__sfetch_emsc_failed_http_status=f.asm.Db).apply(null,arguments)},Jb=f.__sfetch_emsc_failed_buffer_too_small=function(){return(Jb=f.__sfetch_emsc_failed_buffer_too_small=f.asm.Eb).apply(null,arguments)},ma=
f.stackSave=function(){return(ma=f.stackSave=f.asm.Gb).apply(null,arguments)},na=f.stackRestore=function(){return(na=f.stackRestore=f.asm.Hb).apply(null,arguments)},B=f.stackAlloc=function(){return(B=f.stackAlloc=f.asm.Ib).apply(null,arguments)},Nb;function x(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}K=function Ob(){Nb||Pb();Nb||(K=Ob)};
function Qb(a){var b=f._main;a=a||[];a.unshift(ca);var c=a.length,d=B(4*(c+1)),e=d>>2;a.forEach(g=>{var m=F,n=e++,p=pa(g)+1,t=B(p);C(g,la,t,p);m[n]=t});F[e]=0;try{var h=b(c,d);Rb(h)}catch(g){g instanceof x||"unwind"==g||k(1,g)}finally{}}
function Pb(a){function b(){if(!Nb&&(Nb=!0,f.calledRun=!0,!ja)){Ea(ua);Ea(va);if(f.onRuntimeInitialized)f.onRuntimeInitialized();Sb&&Qb(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();xa.unshift(c)}Ea(xa)}}a=a||ba;if(!(0<J)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ya();Ea(ta);0<J||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},
1)):b())}}f.run=Pb;function Rb(a){if(!noExitRuntime){if(f.onExit)f.onExit(a);ja=!0}k(a,new x(a))}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Sb=!0;f.noInitialRun&&(Sb=!1);Pb();
