
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},f),ba=[],ca="./this.program",k=(a,b)=>{throw b;},da="object"==typeof window,l="function"==typeof importScripts,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,r="",fa,u,v,fs,w,ha;
if(ea)r=l?require("path").dirname(r)+"/":__dirname+"/",ha=()=>{w||(fs=require("fs"),w=require("path"))},fa=function(a,b){ha();a=w.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")},v=a=>{a=fa(a,!0);a.buffer||(a=new Uint8Array(a));return a},u=(a,b,c)=>{ha();a=w.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),ba=process.argv.slice(2),"undefined"!=typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof
x))throw a;}),process.on("unhandledRejection",function(a){throw a;}),k=(a,b)=>{if(noExitRuntime)throw process.exitCode=a,b;b instanceof x||y("exiting due to exception: "+b);process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(da||l)l?r=self.location.href:"undefined"!=typeof document&&document.currentScript&&(r=document.currentScript.src),r=0!==r.indexOf("blob:")?r.substr(0,r.replace(/[?#].*/,"").lastIndexOf("/")+1):"",fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);
b.send(null);return b.responseText},l&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),u=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};f.print||console.log.bind(console);var y=f.printErr||console.warn.bind(console);Object.assign(f,aa);aa=null;f.arguments&&(ba=f.arguments);
f.thisProgram&&(ca=f.thisProgram);f.quit&&(k=f.quit);var z;f.wasmBinary&&(z=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!=typeof WebAssembly&&A("no native wasm support detected");var ia,ja=!1;
function ka(a,b,c){var d={string:function(n){var p=0;if(null!==n&&void 0!==n&&0!==n){var t=(n.length<<2)+1;p=B(t);C(n,D,p,t)}return p},array:function(n){var p=B(n.length);la.set(n,p);return p}};a=f["_"+a];var e=[],h=0;if(c)for(var g=0;g<c.length;g++){var m=d[b[g]];m?(0===h&&(h=ma()),e[g]=m(c[g])):e[g]=c[g]}b=a.apply(null,e);b=function(n){0!==h&&na(h);return n}(b)}var oa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function E(a,b){if(a){var c=D,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&oa)a=oa.decode(c.subarray(a,b));else{for(d="";a<b;){var e=c[a++];if(e&128){var h=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=c[a++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}a=d}}else a="";return a}
function C(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function pa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var la,D,qa,ra,F,sa,G,H,I,ta=[],ua=[],va=[],wa=[],xa=[];function ya(){var a=f.preRun.shift();ta.unshift(a)}var J=0,za=null,L=null;function A(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";y(a);ja=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}
function Aa(){return M.startsWith("data:application/octet-stream;base64,")}var M;M="qoiview.wasm";if(!Aa()){var Ba=M;M=f.locateFile?f.locateFile(Ba,r):r+Ba}function Ca(){var a=M;try{if(a==M&&z)return new Uint8Array(z);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function Da(){if(!z&&(da||l)){if("function"==typeof fetch&&!M.startsWith("file://"))return fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Ca()});if(u)return new Promise(function(a,b){u(M,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ca()})}function N(a){for(;0<a.length;)a.shift()(f)}var Ea=0;
function Fa(){for(var a=O.length-1;0<=a;--a)Ga(a);O=[];P=[]}var P=[];function Ha(){if(Ea&&Ia.Kb)for(var a=0;a<P.length;++a){var b=P[a];P.splice(a,1);--a;b.tc.apply(null,b.kc)}}var O=[];function Ga(a){var b=O[a];b.target.removeEventListener(b.Db,b.ec,b.Eb);O.splice(a,1)}function Q(a){function b(d){++Ea;Ia=a;Ha();a.Gb(d);Ha();--Ea}if(a.Fb)a.ec=b,a.target.addEventListener(a.Db,b,a.Eb),O.push(a),Ja||(wa.push(Fa),Ja=!0);else for(var c=0;c<O.length;++c)O[c].target==a.target&&O[c].Db==a.Db&&Ga(c--)}
function Ka(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}var Ja,Ia,La,Ma,Na,Oa,Pa,Qa,Ra,Sa=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0];function R(a){a=2<a?E(a):a;return Sa[a]||("undefined"!=typeof document?document.querySelector(a):void 0)}function Ta(a){return 0>Sa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Ua(a,b,c,d,e,h){La||(La=S(256));a={target:R(a),Db:h,Fb:d,Gb:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=La;C(Ka(g.target),D,n+0,128);C(m,D,n+128,128);I.get(d)(e,n,b)&&g.preventDefault()},Eb:c};Q(a)}
function Va(a,b,c,d,e,h){Ma||(Ma=S(176));a={target:R(a),Kb:!0,Db:h,Fb:d,Gb:function(g){var m=Ma;H[m>>3]=g.timeStamp;var n=m>>2;F[n+2]=g.location;F[n+3]=g.ctrlKey;F[n+4]=g.shiftKey;F[n+5]=g.altKey;F[n+6]=g.metaKey;F[n+7]=g.repeat;F[n+8]=g.charCode;F[n+9]=g.keyCode;F[n+10]=g.which;C(g.key||"",D,m+44,32);C(g.code||"",D,m+76,32);C(g.char||"",D,m+108,32);C(g.locale||"",D,m+140,32);I.get(d)(e,m,b)&&g.preventDefault()},Eb:c};Q(a)}
function Wa(a,b,c){H[a>>3]=b.timeStamp;a>>=2;F[a+2]=b.screenX;F[a+3]=b.screenY;F[a+4]=b.clientX;F[a+5]=b.clientY;F[a+6]=b.ctrlKey;F[a+7]=b.shiftKey;F[a+8]=b.altKey;F[a+9]=b.metaKey;qa[2*a+20]=b.button;qa[2*a+21]=b.buttons;F[a+11]=b.movementX;F[a+12]=b.movementY;c=Ta(c);F[a+13]=b.clientX-c.left;F[a+14]=b.clientY-c.top}
function T(a,b,c,d,e,h){Na||(Na=S(72));a=R(a);Q({target:a,Kb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Db:h,Fb:d,Gb:function(g){g=g||event;Wa(Na,g,a);I.get(d)(e,Na,b)&&g.preventDefault()},Eb:c})}function Xa(a,b,c,d,e){Oa||(Oa=S(260));Q({target:a,Db:e,Fb:d,Gb:function(h){h=h||event;var g=Oa,m=document.pointerLockElement||document.Hb||document.Sb||document.Rb;F[g>>2]=!!m;var n=m&&m.id?m.id:"";C(Ka(m),D,g+4,128);C(n,D,g+132,128);I.get(d)(20,g,b)&&h.preventDefault()},Eb:c})}
function Ya(a,b,c,d,e){Q({target:a,Db:e,Fb:d,Gb:function(h){h=h||event;I.get(d)(38,0,b)&&h.preventDefault()},Eb:c})}
function Za(a,b,c,d){Pa||(Pa=S(36));a=R(a);Q({target:a,Db:"resize",Fb:d,Gb:function(e){e=e||event;if(e.target==a){var h=document.body;if(h){var g=Pa;F[g>>2]=e.detail;F[g+4>>2]=h.clientWidth;F[g+8>>2]=h.clientHeight;F[g+12>>2]=innerWidth;F[g+16>>2]=innerHeight;F[g+20>>2]=outerWidth;F[g+24>>2]=outerHeight;F[g+28>>2]=pageXOffset;F[g+32>>2]=pageYOffset;I.get(d)(10,g,b)&&e.preventDefault()}}},Eb:c})}
function $a(a,b,c,d,e,h){Qa||(Qa=S(1696));a=R(a);Q({target:a,Kb:"touchstart"==h||"touchend"==h,Db:h,Fb:d,Gb:function(g){for(var m,n={},p=g.touches,t=0;t<p.length;++t)m=p[t],m.Ub=m.Vb=0,n[m.identifier]=m;for(t=0;t<g.changedTouches.length;++t)m=g.changedTouches[t],m.Ub=1,n[m.identifier]=m;for(t=0;t<g.targetTouches.length;++t)n[g.targetTouches[t].identifier].Vb=1;p=Qa;H[p>>3]=g.timeStamp;var q=p>>2;F[q+3]=g.ctrlKey;F[q+4]=g.shiftKey;F[q+5]=g.altKey;F[q+6]=g.metaKey;q+=7;var K=Ta(a),ib=0;for(t in n)if(m=
n[t],F[q]=m.identifier,F[q+1]=m.screenX,F[q+2]=m.screenY,F[q+3]=m.clientX,F[q+4]=m.clientY,F[q+5]=m.pageX,F[q+6]=m.pageY,F[q+7]=m.Ub,F[q+8]=m.Vb,F[q+9]=m.clientX-K.left,F[q+10]=m.clientY-K.top,q+=13,31<++ib)break;F[p+8>>2]=ib;I.get(d)(e,p,b)&&g.preventDefault()},Eb:c})}function ab(a,b,c,d,e,h){a={target:R(a),Db:h,Fb:d,Gb:function(g){g=g||event;I.get(d)(e,0,b)&&g.preventDefault()},Eb:c};Q(a)}
function bb(a,b,c,d){Ra||(Ra=S(104));Q({target:a,Kb:!0,Db:"wheel",Fb:d,Gb:function(e){e=e||event;var h=Ra;Wa(h,e,a);H[h+72>>3]=e.deltaX;H[h+80>>3]=e.deltaY;H[h+88>>3]=e.deltaZ;F[h+96>>2]=e.deltaMode;I.get(d)(9,h,b)&&e.preventDefault()},Eb:c})}
function cb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,g){b.drawElementsInstancedANGLE(c,d,e,h,g)})}
function db(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function eb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function fb(a){a.pc=a.getExtension("WEBGL_multi_draw")}
var gb=1,hb=[],U=[],jb=[],kb=[],lb=[],V=[],mb=[],nb={};function W(a){ob||(ob=a)}function pb(a){for(var b=gb++,c=a.length;c<b;c++)a[c]=null;return b}function qb(a,b){a.Hb||(a.Hb=a.getContext,a.getContext=function(d,e){e=a.Hb(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?rb(c,b):0}function rb(a,b){var c=pb(mb),d={nc:c,attributes:b,version:b.ic,Ob:a};a.canvas&&(a.canvas.jc=d);mb[c]=d;("undefined"==typeof b.Tb||b.Tb)&&sb(d);return c}
function sb(a){a||(a=tb);if(!a.hc){a.hc=!0;var b=a.Ob;cb(b);db(b);eb(b);b.mc=b.getExtension("EXT_disjoint_timer_query");fb(b);(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var ob,tb,ub=["default","low-power","high-performance"];function vb(a,b,c,d){for(var e=0;e<a;e++){var h=X[c](),g=h&&pb(d);h?(h.name=g,d[g]=h):W(1282);F[b+4*e>>2]=g}}
function wb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=X.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=X.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:W(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)F[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){W(1280);y("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:W(1280);y("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}F[b>>2]=c}else W(1281)}function xb(a){var b=pa(a)+1,c=S(b);C(a,D,c,b);return c}
function yb(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Y(a){var b=X.dc;if(b){var c=b.Jb[a];"number"==typeof c&&(b.Jb[a]=c=X.getUniformLocation(b,b.bc[a]+(0<c?"["+c+"]":"")));return c}W(1282)}for(var Z=[],X,zb=new Float32Array(288),Ab=0;288>Ab;++Ab)Z[Ab]=zb.subarray(0,Ab+1);
var Kb={M:function(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1},$:function(a,b,c){a=R(a);if(!a)return-4;a=Ta(a);H[b>>3]=a.width;H[c>>3]=a.height;return 0},Sa:function(a,b,c){D.copyWithin(a,b,b+c)},za:function(a,b){function c(d){I.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ra:function(){A("OOM")},I:function(a,b,c,d){Ua(a,b,c,d,12,"blur");return 0},F:function(a,b,c){a=R(a);if(!a)return-4;a.width=b;a.height=c;return 0},J:function(a,b,c,d){Ua(a,b,c,d,13,
"focus");return 0},T:function(a,b,c,d){Va(a,b,c,d,2,"keydown");return 0},R:function(a,b,c,d){Va(a,b,c,d,1,"keypress");return 0},S:function(a,b,c,d){Va(a,b,c,d,3,"keyup");return 0},Z:function(a,b,c,d){T(a,b,c,d,5,"mousedown");return 0},W:function(a,b,c,d){T(a,b,c,d,33,"mouseenter");return 0},V:function(a,b,c,d){T(a,b,c,d,34,"mouseleave");return 0},X:function(a,b,c,d){T(a,b,c,d,8,"mousemove");return 0},Y:function(a,b,c,d){T(a,b,c,d,6,"mouseup");return 0},L:function(a,b,c,d){if(!document||!document.body||
!(document.body.requestPointerLock||document.body.Hb||document.body.Sb||document.body.Rb))return-1;a=R(a);if(!a)return-4;Xa(a,b,c,d,"pointerlockchange");Xa(a,b,c,d,"mozpointerlockchange");Xa(a,b,c,d,"webkitpointerlockchange");Xa(a,b,c,d,"mspointerlockchange");return 0},K:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Hb||document.body.Sb||document.body.Rb))return-1;a=R(a);if(!a)return-4;Ya(a,b,c,d,"pointerlockerror");Ya(a,b,c,d,"mozpointerlockerror");Ya(a,b,c,d,
"webkitpointerlockerror");Ya(a,b,c,d,"mspointerlockerror");return 0},Ma:function(a,b,c,d){Za(a,b,c,d);return 0},N:function(a,b,c,d){$a(a,b,c,d,25,"touchcancel");return 0},O:function(a,b,c,d){$a(a,b,c,d,23,"touchend");return 0},P:function(a,b,c,d){$a(a,b,c,d,24,"touchmove");return 0},Q:function(a,b,c,d){$a(a,b,c,d,22,"touchstart");return 0},H:function(a,b,c,d){ab(a,b,c,d,31,"webglcontextlost");return 0},G:function(a,b,c,d){ab(a,b,c,d,32,"webglcontextrestored");return 0},U:function(a,b,c,d){a=R(a);
return"undefined"!=typeof a.onwheel?(bb(a,b,c,d),0):-1},_:function(a,b){b>>=2;b={alpha:!!F[b],depth:!!F[b+1],stencil:!!F[b+2],antialias:!!F[b+3],premultipliedAlpha:!!F[b+4],preserveDrawingBuffer:!!F[b+5],powerPreference:ub[F[b+6]],failIfMajorPerformanceCaveat:!!F[b+7],ic:F[b+8],oc:F[b+9],Tb:F[b+10],fc:F[b+11],qc:F[b+12],rc:F[b+13]};a=R(a);return!a||b.fc?0:qb(a,b)},Na:function(a,b){a=mb[a];b=E(b);b.startsWith("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&cb(X);"OES_vertex_array_object"==b&&
db(X);"WEBGL_draw_buffers"==b&&eb(X);"WEBGL_multi_draw"==b&&fb(X);return!!a.Ob.getExtension(b)},Pa:function(a){a>>=2;for(var b=0;14>b;++b)F[a+b]=0;F[a]=F[a+1]=F[a+3]=F[a+4]=F[a+8]=F[a+10]=1},Oa:function(a){tb=mb[a];f.lc=X=tb&&tb.Ob;return!a||X?0:-5},D:function(a){X.activeTexture(a)},u:function(a,b){X.attachShader(U[a],V[b])},f:function(a,b){X.bindBuffer(a,hb[b])},q:function(a,b){X.bindFramebuffer(a,jb[b])},qa:function(a,b){X.bindRenderbuffer(a,kb[b])},e:function(a,b){X.bindTexture(a,lb[b])},y:function(a,
b,c,d){X.blendColor(a,b,c,d)},z:function(a,b){X.blendEquationSeparate(a,b)},A:function(a,b,c,d){X.blendFuncSeparate(a,b,c,d)},sa:function(a,b,c,d){X.bufferData(a,c?D.subarray(c,c+b):b,d)},j:function(a,b,c,d){X.bufferSubData(a,b,D.subarray(d,d+c))},eb:function(a){X.clear(a)},aa:function(a,b,c,d){X.clearColor(a,b,c,d)},gb:function(a){X.clearDepth(a)},fb:function(a){X.clearStencil(a)},g:function(a,b,c,d){X.colorMask(!!a,!!b,!!c,!!d)},da:function(a){X.compileShader(V[a])},ma:function(a,b,c,d,e,h,g,m){X.compressedTexImage2D(a,
b,c,d,e,h,m?D.subarray(m,m+g):null)},ka:function(){var a=pb(U),b=X.createProgram();b.name=a;b.Nb=b.Lb=b.Mb=0;b.Qb=1;U[a]=b;return a},fa:function(a){var b=pb(V);V[b]=X.createShader(a);return b},v:function(a){X.cullFace(a)},Aa:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],e=hb[d];e&&(X.deleteBuffer(e),e.name=0,hb[d]=null)}},n:function(a,b){for(var c=0;c<a;++c){var d=F[b+4*c>>2],e=jb[d];e&&(X.deleteFramebuffer(e),e.name=0,jb[d]=null)}},C:function(a){if(a){var b=U[a];b?(X.deleteProgram(b),b.name=
0,U[a]=null):W(1281)}},E:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],e=kb[d];e&&(X.deleteRenderbuffer(e),e.name=0,kb[d]=null)}},i:function(a){if(a){var b=V[a];b?(X.deleteShader(b),V[a]=null):W(1281)}},ya:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],e=lb[d];e&&(X.deleteTexture(e),e.name=0,lb[d]=null)}},m:function(a){X.depthFunc(a)},l:function(a){X.depthMask(!!a)},a:function(a){X.disable(a)},B:function(a){X.disableVertexAttribArray(a)},Ta:function(a,b,c){X.drawArrays(a,b,c)},Ua:function(a,
b,c,d){X.drawElements(a,b,c,d)},c:function(a){X.enable(a)},$a:function(a){X.enableVertexAttribArray(a)},w:function(a){X.frontFace(a)},ta:function(a,b){vb(a,b,"createBuffer",hb)},ra:function(a,b){vb(a,b,"createRenderbuffer",kb)},oa:function(a,b){vb(a,b,"createTexture",lb)},ba:function(a,b){return X.getAttribLocation(U[a],E(b))},b:function(a,b){wb(a,b)},ia:function(a,b,c,d){a=X.getProgramInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,D,d,b):0;c&&(F[c>>2]=b)},t:function(a,b,c){if(c)if(a>=
gb)W(1281);else if(a=U[a],35716==b)a=X.getProgramInfoLog(a),null===a&&(a="(unknown error)"),F[c>>2]=a.length+1;else if(35719==b){if(!a.Nb)for(b=0;b<X.getProgramParameter(a,35718);++b)a.Nb=Math.max(a.Nb,X.getActiveUniform(a,b).name.length+1);F[c>>2]=a.Nb}else if(35722==b){if(!a.Lb)for(b=0;b<X.getProgramParameter(a,35721);++b)a.Lb=Math.max(a.Lb,X.getActiveAttrib(a,b).name.length+1);F[c>>2]=a.Lb}else if(35381==b){if(!a.Mb)for(b=0;b<X.getProgramParameter(a,35382);++b)a.Mb=Math.max(a.Mb,X.getActiveUniformBlockName(a,
b).length+1);F[c>>2]=a.Mb}else F[c>>2]=X.getProgramParameter(a,b);else W(1281)},ca:function(a,b,c,d){a=X.getShaderInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,D,d,b):0;c&&(F[c>>2]=b)},r:function(a,b,c){c?35716==b?(a=X.getShaderInfoLog(V[a]),null===a&&(a="(unknown error)"),F[c>>2]=a?a.length+1:0):35720==b?(a=X.getShaderSource(V[a]),F[c>>2]=a?a.length+1:0):F[c>>2]=X.getShaderParameter(V[a],b):W(1281)},Ba:function(a){var b=nb[a];if(!b){switch(a){case 7939:b=X.getSupportedExtensions()||
[];b=b.concat(b.map(function(d){return"GL_"+d}));b=xb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=X.getParameter(a))||W(1280);b=b&&xb(b);break;case 7938:b=xb("OpenGL ES 2.0 ("+X.getParameter(7938)+")");break;case 35724:b=X.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=xb(b);break;default:W(1280)}nb[a]=b}return b},s:function(a,b){b=E(b);if(a=U[a]){var c=a,d=c.Jb,
e=c.cc,h;if(!d)for(c.Jb=d={},c.bc={},h=0;h<X.getProgramParameter(c,35718);++h){var g=X.getActiveUniform(c,h);var m=g.name;g=g.size;var n=yb(m);n=0<n?m.slice(0,n):m;var p=c.Qb;c.Qb+=g;e[n]=[g,p];for(m=0;m<g;++m)d[p]=m,c.bc[p++]=n}c=a.Jb;d=0;e=b;h=yb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.cc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||X.getUniformLocation(a,b)))return d}else W(1281);return-1},ja:function(a){a=U[a];X.linkProgram(a);a.Jb=0;a.cc={}},x:function(a,b){X.polygonOffset(a,b)},pa:function(a,
b,c,d){X.renderbufferStorage(a,b,c,d)},o:function(a,b,c,d){X.scissor(a,b,c,d)},ea:function(a,b,c,d){for(var e="",h=0;h<b;++h){var g=d?F[d+4*h>>2]:-1;e+=E(F[c+4*h>>2],0>g?void 0:g)}X.shaderSource(V[a],e)},wa:function(a,b,c){X.stencilFunc(a,b,c)},db:function(a,b,c,d){X.stencilFuncSeparate(a,b,c,d)},k:function(a){X.stencilMask(a)},va:function(a,b,c){X.stencilOp(a,b,c)},cb:function(a,b,c,d){X.stencilOpSeparate(a,b,c,d)},la:function(a,b,c,d,e,h,g,m,n){var p=X,t=p.texImage2D;if(n){var q=m-5120;q=1==q?D:
4==q?F:6==q?G:5==q||28922==q?sa:ra;var K=31-Math.clz32(q.BYTES_PER_ELEMENT);n=q.subarray(n>>K,n+e*(d*({5:3,6:4,8:2,29502:3,29504:4}[g-6402]||1)*(1<<K)+4-1&-4)>>K)}else n=null;t.call(p,a,b,c,d,e,h,g,m,n)},d:function(a,b,c){X.texParameteri(a,b,c)},_a:function(a,b,c){if(288>=b)for(var d=Z[b-1],e=0;e<b;++e)d[e]=G[c+4*e>>2];else d=G.subarray(c>>2,c+4*b>>2);X.uniform1fv(Y(a),d)},ha:function(a,b){X.uniform1i(Y(a),b)},Za:function(a,b,c){if(144>=b)for(var d=Z[2*b-1],e=0;e<2*b;e+=2)d[e]=G[c+4*e>>2],d[e+1]=
G[c+(4*e+4)>>2];else d=G.subarray(c>>2,c+8*b>>2);X.uniform2fv(Y(a),d)},Xa:function(a,b,c){if(96>=b)for(var d=Z[3*b-1],e=0;e<3*b;e+=3)d[e]=G[c+4*e>>2],d[e+1]=G[c+(4*e+4)>>2],d[e+2]=G[c+(4*e+8)>>2];else d=G.subarray(c>>2,c+12*b>>2);X.uniform3fv(Y(a),d)},Wa:function(a,b,c){if(72>=b){var d=Z[4*b-1],e=G;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=G.subarray(c>>2,c+16*b>>2);X.uniform4fv(Y(a),d)},Va:function(a,b,c,d){if(18>=b){var e=Z[16*b-1],h=G;d>>=
2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=h[m];e[g+1]=h[m+1];e[g+2]=h[m+2];e[g+3]=h[m+3];e[g+4]=h[m+4];e[g+5]=h[m+5];e[g+6]=h[m+6];e[g+7]=h[m+7];e[g+8]=h[m+8];e[g+9]=h[m+9];e[g+10]=h[m+10];e[g+11]=h[m+11];e[g+12]=h[m+12];e[g+13]=h[m+13];e[g+14]=h[m+14];e[g+15]=h[m+15]}}else e=G.subarray(d>>2,d+64*b>>2);X.uniformMatrix4fv(Y(a),!!c,e)},h:function(a){a=U[a];X.useProgram(a);X.dc=a},ab:function(a,b){X.vertexAttribDivisor(a,b)},bb:function(a,b,c,d,e,h){X.vertexAttribPointer(a,b,c,!!d,e,h)},p:function(a,
b,c,d){X.viewport(a,b,c,d)},La:function(){f.Wb=function(a){0!=Bb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Wb)},Ka:function(){f.ac=function(a){a=a.clipboardData.getData("text");ka("_sapp_emsc_onpaste",["string"],[a])};window.addEventListener("paste",f.ac)},Ja:function(a){f.sc=[];a=E(a);a=document.getElementById(a);f.Xb=function(b){b.stopPropagation();b.preventDefault()};f.Yb=function(b){b.stopPropagation();b.preventDefault()};f.Zb=function(b){b.stopPropagation();
b.preventDefault()};f.$b=function(b){b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;f.Pb=c;Cb(c.length);var d;for(d=0;d<c.length;d++)ka("_sapp_emsc_drop",["number","string"],[d,c[d].name]);Db(b.clientX,b.clientY)};a.addEventListener("dragenter",f.Xb,!1);a.addEventListener("dragleave",f.Yb,!1);a.addEventListener("dragover",f.Zb,!1);a.addEventListener("drop",f.$b,!1)},xa:function(){var a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Ha:function(){var a=
document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Eb()});document.body.append(a)},na:function(a){return 0>a||a>=f.Pb.length?0:f.Pb[a].size},ga:function(a,b,c,d,e){var h=new FileReader;h.onload=function(g){g=g.target.result;g.byteLength>d?Fb(a,0,1,b,0,c,d,e):(D.set(new Uint8Array(g),c),Fb(a,1,0,b,g.byteLength,c,d,e))};h.onerror=function(){Fb(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(f.Pb[a])},Ga:function(){document.getElementById("_sokol_app_input_element").focus()},
ib:function(a){a=E(a);f.Ib=document.getElementById(a);f.Ib||console.log("sokol_app.h: invalid target:"+a);f.Ib.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Ea:function(){window.removeEventListener("beforeunload",f.Wb)},Da:function(){window.removeEventListener("paste",f.ac)},Ca:function(a){a=E(a);a=document.getElementById(a);a.removeEventListener("dragenter",f.Xb);a.removeEventListener("dragleave",f.Yb);a.removeEventListener("dragover",f.Zb);a.removeEventListener("drop",
f.$b)},Ia:function(){f.Ib&&f.Ib.requestPointerLock&&f.Ib.requestPointerLock()},ua:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(D.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Fa:function(){document.getElementById("_sokol_app_input_element").blur()},hb:function(){for(var a=(new URLSearchParams(window.location.search)).entries(),
b=a.next();!b.done;b=a.next())ka("_sargs_add_kvp",["string","string"],[b.value[0],b.value[1]])},Ya:function(a,b,c,d,e,h){b=E(b);var g=new XMLHttpRequest;g.open("GET",b);g.responseType="arraybuffer";var m=0<d;m&&g.setRequestHeader("Range","bytes="+c+"-"+(c+d-1));g.onreadystatechange=function(){if(this.readyState==this.DONE)if(206==this.status||200==this.status&&!m){var n=new Uint8Array(g.response),p=n.length;p<=h?(D.set(n,e),Gb(a,d,p)):Hb(a)}else Ib(a,this.status)};g.send()},Qa:function(a,b){b=E(b);
var c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(this.readyState==this.DONE)if(200==this.status){var d=this.getResponseHeader("Content-Length");Jb(a,d)}else Ib(a,this.status)};c.send()}};
(function(){function a(e){f.asm=e.exports;ia=f.asm.jb;e=ia.buffer;f.HEAP8=la=new Int8Array(e);f.HEAP16=qa=new Int16Array(e);f.HEAP32=F=new Int32Array(e);f.HEAPU8=D=new Uint8Array(e);f.HEAPU16=ra=new Uint16Array(e);f.HEAPU32=sa=new Uint32Array(e);f.HEAPF32=G=new Float32Array(e);f.HEAPF64=H=new Float64Array(e);I=f.asm.zb;ua.unshift(f.asm.kb);J--;f.monitorRunDependencies&&f.monitorRunDependencies(J);0==J&&(null!==za&&(clearInterval(za),za=null),L&&(e=L,L=null,e()))}function b(e){a(e.instance)}function c(e){return Da().then(function(h){return WebAssembly.instantiate(h,
d)}).then(function(h){return h}).then(e,function(h){y("failed to asynchronously prepare wasm: "+h);A(h)})}var d={a:Kb};J++;f.monitorRunDependencies&&f.monitorRunDependencies(J);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return y("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return z||"function"!=typeof WebAssembly.instantiateStreaming||Aa()||M.startsWith("file://")||ea||"function"!=typeof fetch?c(b):fetch(M,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(h){y("wasm streaming compile failed: "+h);y("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.kb).apply(null,arguments)};var S=f._malloc=function(){return(S=f._malloc=f.asm.lb).apply(null,arguments)},Eb=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Eb=f.__sapp_emsc_notify_keyboard_hidden=f.asm.mb).apply(null,arguments)};
f.__sapp_emsc_onpaste=function(){return(f.__sapp_emsc_onpaste=f.asm.nb).apply(null,arguments)};var Bb=f.__sapp_html5_get_ask_leave_site=function(){return(Bb=f.__sapp_html5_get_ask_leave_site=f.asm.ob).apply(null,arguments)},Cb=f.__sapp_emsc_begin_drop=function(){return(Cb=f.__sapp_emsc_begin_drop=f.asm.pb).apply(null,arguments)};f.__sapp_emsc_drop=function(){return(f.__sapp_emsc_drop=f.asm.qb).apply(null,arguments)};
var Db=f.__sapp_emsc_end_drop=function(){return(Db=f.__sapp_emsc_end_drop=f.asm.rb).apply(null,arguments)},Fb=f.__sapp_emsc_invoke_fetch_cb=function(){return(Fb=f.__sapp_emsc_invoke_fetch_cb=f.asm.sb).apply(null,arguments)};f._main=function(){return(f._main=f.asm.tb).apply(null,arguments)};f.__sargs_add_kvp=function(){return(f.__sargs_add_kvp=f.asm.ub).apply(null,arguments)};
var Jb=f.__sfetch_emsc_head_response=function(){return(Jb=f.__sfetch_emsc_head_response=f.asm.vb).apply(null,arguments)},Gb=f.__sfetch_emsc_get_response=function(){return(Gb=f.__sfetch_emsc_get_response=f.asm.wb).apply(null,arguments)},Ib=f.__sfetch_emsc_failed_http_status=function(){return(Ib=f.__sfetch_emsc_failed_http_status=f.asm.xb).apply(null,arguments)},Hb=f.__sfetch_emsc_failed_buffer_too_small=function(){return(Hb=f.__sfetch_emsc_failed_buffer_too_small=f.asm.yb).apply(null,arguments)},ma=
f.stackSave=function(){return(ma=f.stackSave=f.asm.Ab).apply(null,arguments)},na=f.stackRestore=function(){return(na=f.stackRestore=f.asm.Bb).apply(null,arguments)},B=f.stackAlloc=function(){return(B=f.stackAlloc=f.asm.Cb).apply(null,arguments)},Lb;function x(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}L=function Mb(){Lb||Nb();Lb||(L=Mb)};
function Ob(a){var b=f._main;a=a||[];a.unshift(ca);var c=a.length,d=B(4*(c+1)),e=d>>2;a.forEach(g=>{var m=F,n=e++,p=pa(g)+1,t=B(p);C(g,la,t,p);m[n]=t});F[e]=0;try{var h=b(c,d);Pb(h)}catch(g){g instanceof x||"unwind"==g||k(1,g)}finally{}}
function Nb(a){function b(){if(!Lb&&(Lb=!0,f.calledRun=!0,!ja)){N(ua);N(va);if(f.onRuntimeInitialized)f.onRuntimeInitialized();Qb&&Ob(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();xa.unshift(c)}N(xa)}}a=a||ba;if(!(0<J)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ya();N(ta);0<J||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):
b())}}f.run=Nb;function Pb(a){if(!noExitRuntime){if(f.onExit)f.onExit(a);ja=!0}k(a,new x(a))}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var Qb=!0;f.noInitialRun&&(Qb=!1);Nb();
